services:
  srv-pl-dt-eng:
    build:
      context: .
      dockerfile: Dockerfile
    image: img-pl-dt-eng
    container_name: ctnr-pl-dt-eng
    volumes:
      - /home/administrateur/data-engineer-pipeline/data:/app/data
      - /home/administrateur/data-engineer-pipeline/logs:/app/logs
    user: "1000:1000"   # ← Obligatoire !
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
